export const UPLOAD_BOOK_LOADING = "UPLOAD_BOOK_LOADING";
export const UPLOAD_BOOK_SUCCESS = "UPLOAD_BOOK_SUCCESS";
export const UPLOAD_BOOK_ERROR = "UPLOAD_BOOK_ERROR";
export const UPLOAD_BOOK_RESET = "UPLOAD_BOOK_RESET";

export const GET_BOOKS_LOADING = "GET_BOOKS_LOADING";
export const GET_BOOKS_SUCCESS = "GET_BOOKS_SUCCESS";
export const GET_BOOKS_ERROR = "GET_BOOKS_ERROR";
export const GET_BOOKS_RESET = "GET_BOOKS_RESET";

export const GET_BOOK_LOADING = "GET_BOOK_LOADING";
export const GET_BOOK_SUCCESS = "GET_BOOK_SUCCESS";
export const GET_BOOK_ERROR = "GET_BOOK_ERROR";
export const GET_BOOK_RESET = "GET_BOOK_RESET";

export const UPDATE_BOOK_LOADING = "UPDATE_BOOK_LOADING";
export const UPDATE_BOOK_SUCCESS = "UPDATE_BOOK_SUCCESS";
export const UPDATE_BOOK_ERROR = "UPDATE_BOOK_ERROR";
export const UPDATE_BOOK_RESET = "UPDATE_BOOK_RESET";

export const SEARCH_BOOK_LOADING = "SEARCH_BOOK_LOADING";
export const SEARCH_BOOK_SUCCESS = "SEARCH_BOOK_SUCCESS";
export const SEARCH_BOOK_ERROR = "SEARCH_BOOK_ERROR";
export const SEARCH_BOOK_RESET = "SEARCH_BOOK_RESET";

export const SET_SEARCH_TEXT = "SET_SEARCH_TEXT";
export const GET_SEARCH_TEXT = "GET_SEARCH_TEXT";
export const RESET_SEARCH_TEXT = "RESET_SEARCH_TEXT";

export const BOOKS_CATALOG_LOADING = "BOOKS_CATALOG_LOADING";
export const BOOKS_CATALOG_SUCCESS = "BOOKS_CATALOG_SUCCESS";
export const BOOKS_CATALOG_ERROR = "BOOKS_CATALOG_ERROR";
export const BOOKS_CATALOG_RESET = "BOOKS_CATALOG_RESET";
