export const SEARCH_BOOK_LOADING = "SEARCH_BOOK_LOADING";
export const SEARCH_BOOK_SUCCESS = "SEARCH_BOOK_SUCCESS";
export const SEARCH_BOOK_ERROR = "SEARCH_BOOK_ERROR";
export const SEARCH_BOOK_RESET = "SEARCH_BOOK_RESET";

export const SET_SEARCH_TEXT = "SET_SEARCH_TEXT";
export const GET_SEARCH_TEXT = "GET_SEARCH_TEXT";
export const RESET_SEARCH_TEXT = "RESET_SEARCH_TEXT";

export const BOOKS_CATALOG_LOADING = "BOOKS_CATALOG_LOADING";
export const BOOKS_CATALOG_SUCCESS = "BOOKS_CATALOG_SUCCESS";
export const BOOKS_CATALOG_ERROR = "BOOKS_CATALOG_ERROR";
export const BOOKS_CATALOG_RESET = "BOOKS_CATALOG_RESET";
