export const SEARCH_BOOK_LOADING = "SEARCH_BOOK_LOADING";
export const SEARCH_BOOK_SUCCESS = "SEARCH_BOOK_SUCCESS";
export const SEARCH_BOOK_ERROR = "SEARCH_BOOK_ERROR";
export const SEARCH_BOOK_RESET = "SEARCH_BOOK_RESET";

export const SET_SEARCH_TEXT = "SET_SEARCH_TEXT";
export const GET_SEARCH_TEXT = "GET_SEARCH_TEXT";
export const RESET_SEARCH_TEXT = "RESET_SEARCH_TEXT";
